name: Deploy Allure Report

on:
  workflow_run:
    workflows: ["CI Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: []
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure results (Chromium)
        uses: actions/download-artifact@v4
        with:
          name: allure-results-chromium
          path: allure-results/chromium

      - name: Download Allure results (Firefox)
        uses: actions/download-artifact@v4
        with:
          name: allure-results-firefox
          path: allure-results/firefox

      - name: Merge Allure results
        run: |
          mkdir -p merged-results
          cp -r allure-results/chromium/* merged-results/ || true
          cp -r allure-results/firefox/* merged-results/ || true

      - name: Generate Allure HTML report
        uses: simple-elf/allure-report-action@v1.9
        with:
          allure_results: merged-results

      - name: Upload report as Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
