name: Deploy Allure Report

on:
  workflow_run:
    workflows: ["CI Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all Allure results
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_id = context.payload.workflow_run.id;

            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner,
              repo,
              run_id
            });

            const fs = require('fs').promises;
            const path = require('path');
            const admZip = require('adm-zip');

            await fs.mkdir('allure-results', { recursive: true });

            for (const artifact of artifacts.data.artifacts) {
              if (artifact.name.startsWith('allure-results-')) {
                console.log(`Downloading artifact: ${artifact.name}`);
                const download = await github.rest.actions.downloadArtifact({
                  owner,
                  repo,
                  artifact_id: artifact.id,
                  archive_format: 'zip'
                });

                const zip = new admZip(Buffer.from(download.data));
                zip.extractAllTo('allure-results', true);
              }
            }

      - name: Generate Allure HTML report
        uses: simple-elf/allure-report-action@v1.9
        with:
          allure_results: allure-results

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          publish_dir: allure-report